name: airbnb_data_analysis
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - intel-openmp=2025.0.0
  - libexpat=2.7.3
  - libffi=3.4.4
  - libhwloc=2.12.1
  - libiconv=1.16
  - libmpdec=4.0.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openssl=3.0.18
  - pandas=2.3.3
  - pip=25.3
  - python=3.14.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - six=1.17.0
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
prefix: C:\Users\Francielly\anaconda3\envs\airbnb_data_analysis
